#! /usr/bin/python

import binascii
import uuid

f = open("eeprom.tmp", "wb")

# 0-3: signature
f.write('WebL')

# 4-19: serial(16)
uuid_str = str(uuid.uuid4())
serial_str = uuid_str[-16:]
f.write(serial_str)

# 20: LED count; default = 2 lights
f.write(binascii.unhexlify('02'))

f.close()
