#! /usr/bin/python

import binascii
import uuid

f = open("eeprom.tmp", "wb")

# 0-3: signature
f.write('WebL')

# 4-5: version (BCD)
f.write(binascii.unhexlify('0100'))

# 6-21: serial(16 ASCII bytes)
uuid_str = str(uuid.uuid4())
serial_str = uuid_str[-16:]
f.write(serial_str)

# 22: nothing (was LED count; default = 2 lights)
f.write(binascii.unhexlify('00'))

f.close()
