#! /usr/bin/python

import binascii
import uuid
import sys

f = sys.stdout

# 0-3: signature
f.write('WebL')

# 4-5: version (BCD)
f.write(binascii.unhexlify('0100'))

# 6-21: serial(16 ASCII bytes)
uuid_str = str(uuid.uuid4())
serial_str = uuid_str[-16:]
f.write(serial_str)

# Write the built-in light program
prog_parts = [
    '010101f4', # Linear RGB transition, 500 msec
    '00100000', # color red
    '020200',   # pause 512 msec
    '00001000', # green
    '020200',
    '00000010', # blue
    '020200',
    '00101000', # yellow
    '020200',
    '00100010', # magenta
    '020200',
    '00001010', # cyan
    '020200',
                # then alternate green/off a couple times
    '00001000', # green
    '00000000', # off
    '020080',
    '00001000', # green
    '00000000', # off
    '020080',
    '00001000', # green
    '00000000', # off
    '020080',
    ]
program = binascii.unhexlify(''.join(prog_parts))

# 22: program length
f.write(bytearray([len(program)]))

# 23-71: program (up to 48 bytes)
f.write(program)

# not needed if f is sys.stdout
#f.close()
